- design-system/src/main/java/com/poptato/design_system/Color.kt
close #11 
- Color System 값 추가
- 단순하게 값을 추가한 것이라 바로 승인해주셔도 됩니다
> Feat: 디자인시스템 변경사항 반영

- app/src/main/java/com/poptato/di/RepositoryModule.kt
- app/src/main/java/com/poptato/di/ServiceModule.kt
- core/navigation/src/main/java/com/poptato/navigation/NavGraph.kt
- core/src/main/java/com/poptato/core/enums/TodoType.kt
- core/ui/src/main/java/com/poptato/ui/common/TodoBottomSheet.kt
- core/ui/src/main/java/com/poptato/ui/util/DismissKeyboardOnClick.kt
- core/ui/src/main/java/com/poptato/ui/util/DragDropListState.kt
- data/src/main/java/com/poptato/data/base/Endpoints.kt
- data/src/main/java/com/poptato/data/repository/TodoRepositoryImpl.kt
- data/src/main/java/com/poptato/data/service/TodoService.kt
- domain/build.gradle.kts
- domain/src/main/java/com/poptato/domain/model/request/todo/DragDropRequestModel.kt
- domain/src/main/java/com/poptato/domain/model/request/todo/ModifyTodoRequestModel.kt
- domain/src/main/java/com/poptato/domain/model/request/todo/TodoContentModel.kt
- domain/src/main/java/com/poptato/domain/repository/TodoRepository.kt
- domain/src/main/java/com/poptato/domain/usecase/todo/DeleteTodoUseCase.kt
- domain/src/main/java/com/poptato/domain/usecase/todo/DragDropUseCase.kt
- domain/src/main/java/com/poptato/domain/usecase/todo/ModifyTodoUseCase.kt
- feature/backlog/src/main/java/com/poptato/backlog/BacklogEvent.kt
- feature/backlog/src/main/java/com/poptato/backlog/BacklogPageState.kt
- feature/backlog/src/main/java/com/poptato/backlog/BacklogScreen.kt
- feature/backlog/src/main/java/com/poptato/backlog/BacklogViewModel.kt
- feature/src/main/java/com/poptato/feature/MainScreen.kt
close #46 
- 백로그 순서 변경 API 연결
- 백로그 드래그 앤 드롭 애니메이션 수정
https://github.com/user-attachments/assets/5f746340-caa9-49e9-aaa6-0f3e4e5bfaae
> Feat: 백로그 순서 변경 api 연결 

- feature/backlog/src/main/java/com/poptato/backlog/BacklogScreen.kt
- feature/today/src/main/java/com/poptato/today/TodayScreen.kt
- feature/today/src/main/java/com/poptato/today/TodayViewModel.kt
close #66 
- Fix: 투데이 -> 할 일 스와이프 에러 해결 
https://github.com/user-attachments/assets/c6293cab-3609-4f59-84c6-a6eed0e452ca
> Fix: 투데이 -> 할 일 스와이프 에러 해결 

- core/navigation/src/main/java/com/poptato/navigation/NavGraph.kt
- core/ui/src/main/java/com/poptato/ui/common/CommonSnackBar.kt
- core/ui/src/main/java/com/poptato/ui/common/TodoBottomSheet.kt
- design-system/src/main/java/com/poptato/design_system/Color.kt
- design-system/src/main/java/com/poptato/design_system/StringComponent.kt
- feature/backlog/src/main/java/com/poptato/backlog/BacklogEvent.kt
- feature/backlog/src/main/java/com/poptato/backlog/BacklogScreen.kt
- feature/backlog/src/main/java/com/poptato/backlog/BacklogViewModel.kt
- feature/login/src/main/java/com/poptato/login/KaKaoLoginScreen.kt
- feature/src/main/java/com/poptato/feature/MainScreen.kt
- feature/src/main/java/com/poptato/feature/component/BottomNavBarComponent.kt
- feature/today/src/main/java/com/poptato/today/TodayScreen.kt
close #68 
- 토스트 메시지 디자인 수정
- 할일 입력 시 입력창 stoke 부여
- 할일 삭제 토스트 메시지 추가
https://github.com/user-attachments/assets/64007db7-b4a0-40ef-ad77-8dda5fad4ed6
- 구현하는 과정에서 토스트 메시지를 띄워야 한다면 :core:ui 모듈에 있는 CommonSnackBar를 사용하시면 됩니다. 따로 이 컴포저블을 선언해서 사용할 필요없이 MainScreen 상단에 보시면 제가 스낵바를 렌더링하는 함수를 변수로 선언해두었습니다. 이 변수를 navigation graph에 파라미터로 전달해서 사용하시면 됩니다
- MainScreen 코드를 보다가 코드가 너무 길어진 느낌이 있어서 MainScreen에서 사용하는 컴포저블을 component라는 패키지를 만들어서 옮겼습니다. 각자 구현한 파트의 코드가 길어졌다면 MainScreen이 존재하는 모듈을 참고하여 component 패키지를 만들고 컴포저블 코드를 옮겨주세요!
> Feat: 토스트 메시지 디자인 수정

- app/src/main/java/com/poptato/di/TokenAuthenticator.kt
- core/src/main/java/com/poptato/core/util/Extensions.kt
- core/ui/src/main/java/com/poptato/ui/common/DatePickerBottomSheet.kt
- core/ui/src/main/java/com/poptato/ui/common/TodoBottomSheet.kt
- core/ui/src/main/java/com/poptato/ui/util/DragDropListState.kt
- core/ui/src/main/java/com/poptato/ui/util/Extensions.kt
- data/src/main/java/com/poptato/data/repository/AuthRepositoryImpl.kt
- domain/src/main/java/com/poptato/domain/repository/AuthRepository.kt
- domain/src/main/java/com/poptato/domain/usecase/auth/GetTokenUseCase.kt
- domain/src/main/java/com/poptato/domain/usecase/auth/ReissueTokenUseCase.kt
- feature/backlog/build.gradle.kts
- feature/backlog/src/main/java/com/poptato/backlog/BacklogPageState.kt
- feature/backlog/src/main/java/com/poptato/backlog/BacklogScreen.kt
- feature/backlog/src/main/java/com/poptato/backlog/BacklogViewModel.kt
- feature/src/main/java/com/poptato/feature/MainScreen.kt
- feature/src/main/java/com/poptato/feature/MainViewModel.kt
- feature/src/main/java/com/poptato/feature/component/BottomNavBarComponent.kt
- feature/today/src/main/java/com/poptato/today/TodayPageState.kt
- feature/today/src/main/java/com/poptato/today/TodayScreen.kt
- feature/today/src/main/java/com/poptato/today/TodayViewModel.kt
- gradle/libs.versions.toml
close #70 
- 중요 및 마감기한이 있을 때 상단 패딩 수정
- 오늘에서 완료되지 않은 할 일 끼리의 드래그앤드롭
- 바텀시트 마감기한 상하단 구분선 색 변경
- 할일 생성 후 키보드가 내려갔을 때 입력창 포커스 비활성화
- 중요 설정, 마감기한 설정을 동시에 수행한 후 바텀시트를 내리면 중요 설정이 렌더링되지 않는 버그 수정
- 네비게이션바 리플효과 제거
- 토큰 갱신 로직 수정
> Refactor: QA 수정사항 반영

- feature/backlog/src/main/java/com/poptato/backlog/BacklogScreen.kt
close #74 
- 드래그앤드롭 버그 수정
- 스크롤바 삭제
> Fix: 스크롤바 삭제 및 드래그앤드롭 버그 수정

- core/ui/src/main/java/com/poptato/ui/base/BaseViewModel.kt
- data/src/main/java/com/poptato/data/datastore/PoptatoDataStore.kt
- data/src/main/java/com/poptato/data/mapper/TodoIdResponseMapper.kt
- data/src/main/java/com/poptato/data/model/response/backlog/TodoIdResponse.kt
- data/src/main/java/com/poptato/data/repository/BacklogRepositoryImpl.kt
- data/src/main/java/com/poptato/data/service/BacklogService.kt
- domain/src/main/java/com/poptato/domain/model/request/todo/TodoIdModel.kt
- domain/src/main/java/com/poptato/domain/repository/BacklogRepository.kt
- domain/src/main/java/com/poptato/domain/usecase/backlog/CreateBacklogUseCase.kt
- feature/backlog/src/main/java/com/poptato/backlog/BacklogViewModel.kt
- feature/src/main/java/com/poptato/feature/MainActivity.kt
- feature/src/main/java/com/poptato/feature/MainPageState.kt
- feature/src/main/java/com/poptato/feature/MainScreen.kt
- feature/src/main/java/com/poptato/feature/MainViewModel.kt
- feature/today/src/main/java/com/poptato/today/TodayViewModel.kt
close #76 
- 백로그 생성 로직 수정
- MainScreen UI, 비즈니스 로직 분리
- progressbar 렌더링 로직 수정
- 코틀린 코딩 컨벤션 적용
- 모든 뷰모델 함수 단일 책임 원칙 적용
> Refactor: 중간 피드백 반영

- feature/history/src/main/java/com/potato/history/HistoryViewModel.kt
#109
오늘 기준으로 한 일 없을 시 검은 동그라미, 한 일 있을 시 별 아이콘으로 나오도록 함
https://github.com/user-attachments/assets/c49669da-2c5d-4ef7-9192-87bc3e91e1ae
> Fix: calendar icon 수정

- core/navigation/src/main/java/com/poptato/navigation/NavGraph.kt
- core/ui/src/main/java/com/poptato/ui/common/CategoryBottomSheet.kt
- data/src/main/java/com/poptato/data/mapper/UserDataResponseMapper.kt
- data/src/main/java/com/poptato/data/model/response/mypage/UserDataResponse.kt
- design-system/src/main/java/com/poptato/design_system/StringComponent.kt
- feature/mypage/src/main/java/com/poptato/mypage/MyPageScreen.kt
- feature/setting/src/main/java/com/poptato/setting/userdata/UserDataScreen.kt
- feature/yesterdaylist/src/main/java/com/poptato/yesterdaylist/YesterdayListScreen.kt
- close #110 
- 카테고리 없을 시 바텀시트 수정
https://github.com/user-attachments/assets/9e4d9a21-1b52-41f4-b9a9-3f8ab16a933c
> Refactor: 카테고리 없을 시 바텀시트 수정

- feature/backlog/src/main/java/com/poptato/backlog/BacklogViewModel.kt
> Refactor: snapshotList Mutex 적용

- app/build.gradle.kts
- app/src/main/java/com/poptato/app/PoptatoApplication.kt
- app/src/main/java/com/poptato/di/AnalyticsModule.kt
- app/src/main/java/com/poptato/di/TokenAuthenticator.kt
- build-logic/src/main/java/com/poptato/plugin/CommonConfigs.kt
- core/src/main/java/com/poptato/core/util/TimeFormatter.kt
- core/ui/src/main/java/com/poptato/ui/common/CalendarBottomSheet.kt
- core/ui/src/main/java/com/poptato/ui/common/TodoBottomSheet.kt
- core/ui/src/main/java/com/poptato/ui/util/AnalyticsManager.kt
- feature/backlog/src/main/java/com/poptato/backlog/BacklogScreen.kt
- feature/backlog/src/main/java/com/poptato/backlog/BacklogViewModel.kt
- feature/category/src/main/java/com/poptato/category/CategoryViewModel.kt
- feature/login/src/main/java/com/poptato/login/KaKaoLoginViewModel.kt
- feature/mypage/src/main/java/com/poptato/mypage/MyPageScreen.kt
- feature/setting/src/main/java/com/poptato/setting/servicedelete/ServiceDeleteScreen.kt
- feature/src/main/java/com/poptato/feature/MainActivity.kt
- feature/src/main/java/com/poptato/feature/MainScreen.kt
- feature/today/src/main/java/com/poptato/today/TodayScreen.kt
- feature/today/src/main/java/com/poptato/today/TodayViewModel.kt
- feature/today/src/test/java/com/poptato/today/ExampleUnitTest.kt
- gradle.properties
- gradle/libs.versions.toml
> Feat: Clarity, GA 도입

- app/src/main/java/com/poptato/di/TokenAuthenticator.kt
- data/src/main/java/com/poptato/data/base/ApiResponse.kt
- data/src/main/java/com/poptato/data/model/response/backlog/BacklogItemResponse.kt
- data/src/main/java/com/poptato/data/model/response/today/TodayItemResponse.kt
- domain/src/main/java/com/poptato/domain/base/ApiException.kt
> Refactor: 서버 응답 data class 변경

- core/ui/src/main/java/com/poptato/ui/util/DragDropListState.kt
- data/src/main/java/com/poptato/data/base/Endpoints.kt
- data/src/main/java/com/poptato/data/repository/CategoryRepositoryImpl.kt
- data/src/main/java/com/poptato/data/service/CategoryService.kt
- domain/src/main/java/com/poptato/domain/model/request/category/CategoryDragDropRequestModel.kt
- domain/src/main/java/com/poptato/domain/repository/CategoryRepository.kt
- domain/src/main/java/com/poptato/domain/usecase/category/CategoryDragDropUseCase.kt
- feature/backlog/src/main/java/com/poptato/backlog/BacklogScreen.kt
- feature/backlog/src/main/java/com/poptato/backlog/BacklogViewModel.kt
- feature/today/src/main/java/com/poptato/today/TodayScreen.kt
> Feat: 카테고리 순서 변경

- core/navigation/src/main/java/com/poptato/navigation/NavGraph.kt
- core/ui/src/main/java/com/poptato/ui/util/AnalyticsManager.kt
- data/src/main/java/com/poptato/data/datastore/PoptatoDataStore.kt
- data/src/main/java/com/poptato/data/repository/YesterdayRepositoryImpl.kt
- domain/src/main/java/com/poptato/domain/repository/YesterdayRepository.kt
- domain/src/main/java/com/poptato/domain/usecase/yesterday/GetShouldShowYesterdayUseCase.kt
- domain/src/main/java/com/poptato/domain/usecase/yesterday/SetShouldShowYesterdayUseCase.kt
- feature/backlog/src/main/java/com/poptato/backlog/BacklogPageState.kt
- feature/backlog/src/main/java/com/poptato/backlog/BacklogScreen.kt
- feature/backlog/src/main/java/com/poptato/backlog/BacklogViewModel.kt
- feature/splash/src/main/java/com/poptato/splash/SplashViewModel.kt
- feature/yesterdaylist/src/main/java/com/poptato/yesterdaylist/YesterdayListPageState.kt
- feature/yesterdaylist/src/main/java/com/poptato/yesterdaylist/YesterdayListScreen.kt
- feature/yesterdaylist/src/main/java/com/poptato/yesterdaylist/YesterdayListViewModel.kt
- gradle/libs.versions.toml
> Refactor: 어제 한 일 페이지 로직 수정

- app/src/main/java/com/poptato/di/TokenAuthenticator.kt
- core/ui/build.gradle.kts
- core/ui/src/main/java/com/poptato/ui/util/FCMManager.kt
- domain/src/main/java/com/poptato/domain/model/request/ReissueRequestModel.kt
- feature/login/src/main/java/com/poptato/login/KaKaoLoginScreen.kt
- feature/splash/src/main/java/com/poptato/splash/SplashViewModel.kt
> Refactor: 토큰 갱신 api 요청 data class 수정

- data/src/main/java/com/poptato/data/base/Endpoints.kt
- data/src/main/java/com/poptato/data/repository/YesterdayRepositoryImpl.kt
- data/src/main/java/com/poptato/data/service/YesterdayService.kt
- domain/src/main/java/com/poptato/domain/model/request/todo/TodoIdsModel.kt
- domain/src/main/java/com/poptato/domain/repository/YesterdayRepository.kt
- domain/src/main/java/com/poptato/domain/usecase/yesterday/UpdateYesterdayTodoCompletionUseCase.kt
- feature/backlog/src/main/java/com/poptato/backlog/BacklogScreen.kt
- feature/backlog/src/main/java/com/poptato/backlog/BacklogViewModel.kt
- feature/yesterdaylist/src/main/java/com/poptato/yesterdaylist/YesterdayListScreen.kt
- feature/yesterdaylist/src/main/java/com/poptato/yesterdaylist/YesterdayListViewModel.kt
- gradle.properties
- close #131 
https://github.com/user-attachments/assets/df2e9d21-4830-4c18-9ac3-9a96bf1232c6
> Feat: 어제 한 일 완료 api 연결

- core/navigation/src/main/java/com/poptato/navigation/NavGraph.kt
- core/navigation/src/main/java/com/poptato/navigation/NavRoutes.kt
- core/ui/src/main/java/com/poptato/ui/base/BaseViewModel.kt
- domain/src/main/java/com/poptato/domain/model/response/category/CategoryScreenContentModel.kt
- feature/backlog/src/main/java/com/poptato/backlog/BacklogScreen.kt
- feature/backlog/src/main/java/com/poptato/backlog/BacklogViewModel.kt
- feature/category/src/main/java/com/poptato/category/CategoryEvent.kt
- feature/category/src/main/java/com/poptato/category/CategoryPageState.kt
- feature/category/src/main/java/com/poptato/category/CategoryScreen.kt
- feature/category/src/main/java/com/poptato/category/CategoryViewModel.kt
- feature/login/src/main/java/com/poptato/login/KaKaoLoginScreen.kt
- feature/splash/src/main/java/com/poptato/splash/SplashScreen.kt
- feature/src/main/java/com/poptato/feature/MainScreen.kt
> Refactor: 카테고리 QA 요청사항 반영

- feature/backlog/src/main/java/com/poptato/backlog/BacklogPageState.kt
- feature/backlog/src/main/java/com/poptato/backlog/BacklogScreen.kt
- feature/backlog/src/main/java/com/poptato/backlog/BacklogViewModel.kt
- gradle.properties
> Refactor: BacklogScreen 렌더링 최적화

- data/src/main/java/com/poptato/data/base/Endpoints.kt
- data/src/main/java/com/poptato/data/repository/TodoRepositoryImpl.kt
- data/src/main/java/com/poptato/data/service/TodoService.kt
- domain/src/main/java/com/poptato/domain/model/request/todo/RoutineRequestModel.kt
- domain/src/main/java/com/poptato/domain/repository/TodoRepository.kt
- domain/src/main/java/com/poptato/domain/usecase/todo/UpdateRoutineUseCase.kt
> Fix: Lint 오류 수정

- core/navigation/src/main/java/com/poptato/navigation/NavGraph.kt
- core/navigation/src/main/java/com/poptato/navigation/NavRoutes.kt
- data/src/main/java/com/poptato/data/base/Endpoints.kt
- data/src/main/java/com/poptato/data/repository/MyPageRepositoryImpl.kt
- data/src/main/java/com/poptato/data/service/MyPageService.kt
- design-system/src/main/java/com/poptato/design_system/StringComponent.kt
- domain/src/main/java/com/poptato/domain/model/request/mypage/UserCommentRequest.kt
- domain/src/main/java/com/poptato/domain/repository/MyPageRepository.kt
- domain/src/main/java/com/poptato/domain/usecase/mypage/SendCommentUseCase.kt
- feature/mypage/src/main/java/com/poptato/mypage/MyPageEvent.kt
- feature/mypage/src/main/java/com/poptato/mypage/MyPageScreen.kt
- feature/mypage/src/main/java/com/poptato/mypage/MyPageViewModel.kt
- feature/mypage/src/main/java/com/poptato/mypage/comment/UserCommentScreen.kt
- feature/src/main/java/com/poptato/feature/MainScreen.kt
- gradle.properties
> Feat: 개발자에게 의견 보내기 구현 
